@SkyQuery.AppGateway_HostAddress = http://localhost:5152

GET {{SkyQuery.AppGateway_HostAddress}}/weatherforecast/
Accept: application/json

###

### Request to Image Entry endpoint
POST {{SkyQuery.AppGateway_HostAddress}}/entry/image
Content-Type: application/json
Accept: application/json
{
  "userId": "AA6DE4ED-1F05-4999-80E6-D465B02E2079",
  "mgrs": "32UNG 3032 2526"
}
